geometry_msgs/Pose goal_pose
sensor_msgs/JointState seed_state
int32 num_solutions_to_return
---
bool[] success
string message
float32 planning_time
moveit_msgs/MoveItErrorCodes error_code
sensor_msgs/JointState[] joint_states
---
string status
