"""
Test launch file for the suites generated by ros2_test_compose.

A thin wrapper around gen_traj.launch.py: same nodes, same URDF/descriptor
resolution paths, with arguments pinned so the suites are fast, deterministic
and hardware-free:

- gui:=false             drops RViz (avoids ~15s of SIGINT->SIGTERM->SIGKILL per
                          suite, and the -9/-6 exit codes that pollute
                          assertExitCodes)
- voxel_size:=0.05        pinned rather than inherited. It matches the
                          production default, but test_object.yaml (case 04)
                          asserts an exact voxel count, so the value is stated
                          here instead of tracking whatever production picks.
- mapper_extent_xyz       [2.0, 2.0, 2.0], which at 0.05 m gives a 40^3 = 64000
                          voxel grid -- the count case 04 expects
- robot:=emulator         no real arm is present under test
- robot_config_file       the test configs are Kortex-shaped, so the model comes
                          from the kortex repo (iki_kortex_moveit_config) rather
                          than being baked into this robot-abstract package.
                          Override with robot_config_file:=<path> to run against
                          a different robot.
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration


def generate_launch_description():
    isaac_ros_cumotion_launch_dir = os.path.join(
        get_package_share_directory('isaac_ros_cumotion'), 'launch')

    # Default model for the Kortex-shaped test configs, resolved from the kortex
    # repo's installed share. Overridable to run the suites against any robot.
    default_robot_config = os.path.join(
        get_package_share_directory('iki_kortex_moveit_config'),
        'config', 'kortex.curobo.yml')

    return LaunchDescription([
        DeclareLaunchArgument(
            'robot_config_file',
            default_value=default_robot_config,
            description='cuRobo robot config for the test suites (default: Kortex model)',
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(isaac_ros_cumotion_launch_dir, 'gen_traj.launch.py')
            ),
            launch_arguments={
                'gui': 'false',
                'voxel_size': '0.05',
                'mapper_extent_xyz': '[2.0, 2.0, 2.0]',
                'robot': 'emulator',
                'robot_config_file': LaunchConfiguration('robot_config_file'),
            }.items()
        ),
    ])
