# Request ESDF computation and clearing.
# Mirrors the nvblox_msgs/EsdfAndGradients interface to allow a drop-in replacement.

bool update_esdf
bool visualize_esdf
bool use_aabb
string frame_id
geometry_msgs/Point aabb_min_m
geometry_msgs/Vector3 aabb_size_m
geometry_msgs/Point[] aabbs_to_clear_min_m
geometry_msgs/Vector3[] aabbs_to_clear_size_m
geometry_msgs/Point[] spheres_to_clear_center_m
float32[] spheres_to_clear_radius_m
---
bool success
float32 voxel_size_m
geometry_msgs/Point origin_m
std_msgs/Float32MultiArray esdf_and_gradients
